version: "3.9"

services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${AP_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${AP_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AP_POSTGRES_DATABASE}
    ports:
      - "5432:5432"

  backend:
    image: activepieces/activepieces:latest
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=api.yourdomain.com
      - LETSENCRYPT_HOST=api.yourdomain.com
      - LETSENCRYPT_EMAIL=your@email.com
    expose:
      - "3000"

  frontend:
    image: activepieces/ui:latest
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=yourdomain.com
      - LETSENCRYPT_HOST=yourdomain.com
      - LETSENCRYPT_EMAIL=your@email.com
    expose:
      - "80"

  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  acme-companion:
    image: nginxproxy/acme-companion
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html